/**
 * Core domain types for the research tracker.
 *
 * The mental model:
 *
 *   - A Paper is a long-running project. It does NOT advance through stages.
 *     It accumulates work across six parallel, non-linear stages.
 *
 *   - A Stage is a CATEGORY OF WORK: ideation, literature, drafting, code,
 *     experiments, aesthetics. At any moment, a paper can have active work
 *     in several stages at once.
 *
 *   - A Task is the unit of work. Each task belongs to exactly one stage and
 *     one paper. Tasks are what moves across the Kanban board — NOT papers.
 *
 *   - Per-paper stage completion is computed automatically from the tasks
 *     in that stage, but the user can manually mark a stage complete to
 *     override the auto-computed value.
 *
 *   - Ideation is special: it has seven sub-stages corresponding to the
 *     conceptual parts of a paper (Title, Gap, Hypothesis, ...). These
 *     live as free-form notes on the paper — they are the "thinking layer"
 *     beneath the task layer.
 */

export type PaperId = string;

/** The six top-level stages. Non-linear; a paper can have tasks in any subset. */
export const STAGES = [
  'ideation',
  'literature',
  'drafting',
  'code',
  'experiments',
  'aesthetics',
] as const;

export type Stage = (typeof STAGES)[number];

export const STAGE_LABELS: Record<Stage, string> = {
  ideation: 'Ideation',
  literature: 'Literature Review',
  drafting: 'Drafting',
  code: 'Code',
  experiments: 'Experiments',
  aesthetics: 'Aesthetics',
};

export const STAGE_DESCRIPTIONS: Record<Stage, string> = {
  ideation: 'Clarifying the research question, hypothesis, and conceptual method.',
  literature: 'Finding, reading, and organizing citations and related work.',
  drafting: 'Writing the manuscript text — paragraphs, sections, revisions.',
  code: 'Implementation, scripts, notebooks, infrastructure.',
  experiments: 'Running experiments, gathering results, statistics, evaluation.',
  aesthetics: 'Figures, diagrams, plots, schematics, visual polish.',
};

/**
 * Ideation sub-stages — the conceptual "parts" of a paper. These live as
 * free-form note fields on the Paper object, not as separate entities.
 * They are NOT tasks and do NOT move through the Kanban.
 */
export const IDEATION_SUBSTAGES = [
  'title',
  'gap',
  'hypothesis',
  'method',
  'experimentDesign',
  'outlook',
  'conclusion',
] as const;

export type IdeationSubstage = (typeof IDEATION_SUBSTAGES)[number];

export const IDEATION_SUBSTAGE_LABELS: Record<IdeationSubstage, string> = {
  title: 'Title',
  gap: 'Research Question / Gap',
  hypothesis: 'Hypothesis',
  method: 'Methodology (concept)',
  experimentDesign: 'Experiment design (concept)',
  outlook: 'Outlook',
  conclusion: 'Conclusion',
};

/**
 * Per-ideation-substage note: free-form text plus a 0–4 maturity score
 * indicating how clear the idea is in the author's head.
 *
 *   0 Empty    — nothing there yet
 *   1 Vague    — rough intuition, not articulable
 *   2 Drafted  — can explain it but it has holes
 *   3 Solid    — could defend it in a meeting
 *   4 Defended — survived adversarial pushback or review
 */
export type MaturityLevel = 0 | 1 | 2 | 3 | 4;

export const MATURITY_LABELS: Record<MaturityLevel, string> = {
  0: 'Empty',
  1: 'Vague',
  2: 'Drafted',
  3: 'Solid',
  4: 'Defended',
};

export interface IdeationNote {
  maturity: MaturityLevel;
  notes: string;
}

/**
 * Per-paper, per-stage completion status.
 *
 * `auto` is derived from the paper's tasks in that stage (done / total).
 * `manualDone` is an explicit user override; when true, the stage is
 * considered complete regardless of task counts. It is STICKY — adding a
 * new open task to a manually-completed stage does not un-mark it, but
 * the UI will surface the disagreement.
 */
export interface StageStatus {
  manualDone: boolean;
}

/**
 * Task — the unit of work. Lives on the Kanban board.
 *
 *   status: 'todo' | 'in_progress' | 'done'
 *     'in_progress' tasks count toward the WIP limit.
 *
 *   source: 'manual' | 'suggested'
 *     Suggested tasks were generated by the rules engine and accepted by
 *     the user. They become ordinary tasks once accepted.
 *
 *   isFocus: boolean
 *     At most one task in the whole app holds focus = true. The Focus
 *     view foregrounds it over algorithmic suggestions.
 */
export type TaskStatus = 'todo' | 'in_progress' | 'done';

export const TASK_STATUS_LABELS: Record<TaskStatus, string> = {
  todo: 'To do',
  in_progress: 'In progress',
  done: 'Done',
};

/**
 * Task criteria — the six dimensions of the Multi-Criteria Decision Making
 * utility model used to prioritize tasks.
 *
 * The utility function is:
 *    U = (V * P * (1 + I) * T) / (C + S)
 *
 * where S (switch cost) is computed on demand from the currently-focused
 * task's paper/stage, and is NOT stored on the task itself.
 *
 * Scales are small, discrete, and calibrated against each other. Not
 * empirically derived — the point is to make the axes explicit so
 * tradeoffs are visible.
 *
 * Grounded in: Expected Utility Theory, WSJF (Weighted Shortest Job First),
 * temporal discounting, cognitive load / task-switching literature.
 */
export type Impact = 0.3 | 0.6 | 1.0;
export type Probability = 0.4 | 0.7 | 0.9;
export type InfoGain = 0 | 0.5 | 1.0;
export type TimeSensitivity = 0.3 | 0.6 | 1.0;
export type Effort = 1 | 2 | 3;

export interface TaskCriteria {
  /** V — how much does this move the paper toward acceptance? */
  impact: Impact;
  /** P — how likely is this task to succeed? */
  probability: Probability;
  /** I — how much does completing this reshape what to do next? */
  infoGain: InfoGain;
  /** T — how much does delay reduce the value? */
  timeSensitivity: TimeSensitivity;
  /** C — time / energy cost. */
  effort: Effort;
}

export const IMPACT_LABELS: Record<Impact, string> = {
  0.3: 'Polish',
  0.6: 'Clarify',
  1.0: 'Core claim',
};

export const IMPACT_HELP: Record<Impact, string> = {
  0.3: 'Nice-to-have polish — fixes a small issue without changing the core message',
  0.6: 'Improves argument, clarity, or removes a minor rejection risk',
  1.0: 'Affects the core claim, main result, or the paper\'s acceptance prospects',
};

export const PROBABILITY_LABELS: Record<Probability, string> = {
  0.4: 'Risky',
  0.7: 'Moderate',
  0.9: 'Reliable',
};

export const PROBABILITY_HELP: Record<Probability, string> = {
  0.4: 'Uncertain outcome — new method, unclear result, could fail',
  0.7: 'Moderate — small experiment or task with a known failure mode',
  0.9: 'Near-deterministic — writing, formatting, collecting existing material',
};

export const INFO_GAIN_LABELS: Record<InfoGain, string> = {
  0: 'Execution',
  0.5: 'Local',
  1.0: 'Direction',
};

export const INFO_GAIN_HELP: Record<InfoGain, string> = {
  0: 'Pure execution — result is known in advance',
  0.5: 'Reduces local uncertainty — informs one decision',
  1.0: 'Shapes the plan — a key experiment, baseline, or reading',
};

export const TIME_SENSITIVITY_LABELS: Record<TimeSensitivity, string> = {
  0.3: 'No rush',
  0.6: 'Medium-term',
  1.0: 'Deadline-critical',
};

export const TIME_SENSITIVITY_HELP: Record<TimeSensitivity, string> = {
  0.3: 'No external deadline pulling on this',
  0.6: 'Relevant within weeks',
  1.0: 'Blocks a deadline or a collaborator',
};

export const EFFORT_LABELS: Record<Effort, string> = {
  1: '< 2 hours',
  2: 'Half-day',
  3: 'Multi-day',
};

export const EFFORT_HELP: Record<Effort, string> = {
  1: 'Less than two hours of focused work',
  2: 'A half-day session',
  3: 'Spans multiple days or sessions',
};

export interface Task {
  id: string;
  paperId: PaperId;
  stage: Stage;
  title: string;
  status: TaskStatus;
  source: 'manual' | 'suggested';
  /** Why the rules engine suggested this. Empty for manual tasks. */
  rationale?: string;
  createdAt: string;
  completedAt?: string;
  /** Optional free-form notes on the task itself. */
  notes?: string;
  isFocus?: boolean;
  /**
   * MCDM criteria used to compute the task's utility score.
   * Required for all v3 tasks; migrated from defaults for older schemas.
   */
  criteria: TaskCriteria;
}

/**
 * Paper — a research project. Does NOT have a single stage. Accumulates
 * work in the form of tasks across all six stages.
 */
export interface Paper {
  id: PaperId;
  title: string;
  shortName: string;
  venue?: string;
  deadline?: string;
  /** Per-stage manual overrides. Auto-completion is computed from tasks. */
  stageStatus: Record<Stage, StageStatus>;
  /** Free-form conceptual notes — one per ideation sub-stage. */
  ideationNotes: Record<IdeationSubstage, IdeationNote>;
  createdAt: string;
  updatedAt: string;
  links: { label: string; url: string }[];
  collaborators: string;
  /** If true, the paper is paused/shelved — hidden from active views. */
  paused: boolean;
  /** If true, the paper is submitted or published — shown but deprioritised. */
  archived: boolean;
}

/**
 * Diary entry — timestamped reflection. Can be attached to a paper or
 * stand alone.
 */
export interface DiaryEntry {
  id: string;
  paperId?: PaperId;
  kind: 'log' | 'weekly-review';
  content: string;
  createdAt: string;
}

/**
 * The entire serializable application state.
 */
export interface AppState {
  schemaVersion: 3;
  papers: Paper[];
  tasks: Task[];
  diary: DiaryEntry[];
  settings: {
    /** Max tasks in 'in_progress' status across all papers. */
    wipLimit: number;
    /** Days of inactivity before a paper is flagged as stale. */
    staleDays: number;
  };
  lastSavedAt: string;
}
